### ISSUE TITLE
Windows Version?

### ISSUE THREAD

**Issue by stunslave** [tslashd/SurfTimer-GOTV#4]
Tried using https://github.com/peace-maker/sourcetvmanager/releases/tag/v1.1 wont load the extension or plugin.
```
L 02/06/2022 - 13:26:51: [STVM] Failed to find host_client pointer. Server might crash when executing commands on SourceTV bot.
L 02/06/2022 - 13:26:52: [SM] Unable to load plugin "SurfTimer-GOTV.smx": Required extension "SourceTV Manager" file("sourcetvmanager.ext") not running
```

**Comment by tslashd** [comment]
Did you use the windows version for SourceTV Manager extension?

**Comment by stunslave** [comment]
Yes I tried using the SourceTV Manager extension for windows.. it wouldn't load.

I also tried the gamedata from SourceTV Manager and also from SurfTimer-GOTV.. 
Neither worked.. both where unable to load the extension + plugin.. 

:::Everything I tried gave the same error:::
`[SM] Unable to load plugin "SurfTimer-GOTV.smx": Required extension "SourceTV Manager" file("sourcetvmanager.ext") not running`

**Comment by tslashd** [comment]
For windows servers you have to use the **_*.dll_** file for SourceTV Manager extension, instead of **_*.so_** (make sure you are using the correct ones and try again)
To me it seems like this error comes from your server not being able to load SourceTV Manager for some reason, it is not an issue deriving from the GOTV plugin

**Comment by stunslave** [comment]
I am using the windows file (dll), as said above. 
I still get the exact same issue. 

Will wait for a windows version added to the plugin b4 I try it again.
